name: Reddit bot

on:
  schedule:
    - cron: '*/30 * * * *' # Run the job every 30 minutes
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install praw
    - name: Run bot
      run: python RedditEnRancais.py
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
